## Numpy

Se non avete installato numpy, un-commentate la cella qui sotto ed eseguitela. Il `!` indica a Jupyter di eseguire un comando "fuori" da Python - in questo caso, un comando che da terminale chiede a `pip` di installare numpy.

In [5]:
# !pip install numpy

  Using cached numpy-1.22.3-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)


Questa è la sintassi che si usa per importare i moduli esterni. `as np` indica che useremo l'abbreviazione `np` anziché `numpy` quando dovremo usare una funzione, ma _in teoria_ potrebbe essere qualsiasi cosa. La regola che si segue è di usare l'abbreviazione specificata dalla documentazione della libreria - in questo caso, `np`.

In [1]:
import numpy as np

Un esempio di invocazione di un comando della libreria. In questo caso l'attributo `__version__` restituisce una stringa che riporta la versione che abbiamo installato della libreria:

In [2]:
print(np.__version__)

1.22.3


La struttura fondamentale di numpy è il `ndarray`, cioè un array (matrice) n-dimensionale.

In [3]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


Un array è diverso da una lista:

In [4]:
lista = [1,2,3,4]
print(lista)

[1, 2, 3, 4]


In [5]:
print(
    type(lista),
    "\n", # <- crea una linea bianca
    type(array)
)

<class 'list'> 
 <class 'numpy.ndarray'>


Innanzitutto, possiamo creare facilmente array in due o più dimensioni, contrariamente alle liste:

In [7]:
lista_2d = [[1,2], [3,4]]
print(lista_2d)

array_2d = np.array([[1,2], [3,4]])
print(array_2d)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


Possiamo vedere quanti elementi ha l'array, senza usare `len()`:

In [11]:
array_2d.size

4

Ma anche il numero di dimensioni:

In [12]:
array_2d.shape

(2, 2)

In questo caso, `array_2d` ha due righe e due colonne.

Creare array complessi è molto semplice usando il metodo `.reshape()`:

In [15]:
matrice_3x3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, -1)

matrice_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
matrice_3x3.shape

(3, 3)

In questo caso, `reshape()` prende come argomento il numero di righe che vogliamo, 3. `-1` indica a numpy di calcolare automaticamente quanti elementi mettere nell'altra dimensione:

In [31]:
array_3d = matrice_3x3.reshape(1, 3, -1)
array_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
array_3d.shape

(1, 3, 3)

Anche se si tratta di un array difficile da visualizzare perché ha tre dimensioni.

Per creare un array possiamo usare qualsiasi `Iterable`:

In [42]:
np.array(range(18)).reshape(2, 3, -1)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

E possiamo anche trasporli velocemente:

In [43]:
matrice_3x3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Per farlo con Python avremmo dovuto usare due for loop "nestati":

In [53]:
lista_3x3 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

lista_trasposta = [[None, None, None], [None, None, None], [None, None, None]]

for i in range(3):
    for j in range(3):
        lista_trasposta[i][j] = lista_3x3[j][i]
        
print(lista_trasposta)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


E questa operazione diventa estremamente più lenta e laboriosa più la matrice diventa grande.

In [15]:
array_2d.dtype

dtype('int64')

In [13]:
np.array(["ciao", 1])

array(['ciao', '1'], dtype='<U21')

In [16]:
grossa_lista = [1] * 100_000
print(len(grossa_lista))

10000


In [21]:
grossa_lista = list(range(1_000_000))
print(grossa_lista[:5])

[0, 1, 2, 3, 4]


In [22]:
import sys

sys.getsizeof(grossa_lista)

8000056

In [28]:
%%timeit
for element in grossa_lista:
    element += 1

64.3 ms ± 5.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
grosso_array = np.linspace(1, 1_000_000, 1_000_000)
grosso_array.shape

(1000000,)

In [42]:
%timeit grosso_array + 1

2.15 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [43]:
import math

print(math.sqrt(4))

2.0


In [44]:
from math import sqrt
print(sqrt(4))

2.0


In [50]:
%%timeit
nuova_lista_grossa = []

for element in grossa_lista[:100]:
    nuova_lista_grossa.append(sqrt(element))

21.7 µs ± 3.71 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
%%timeit
np.sqrt(grosso_array)

4.33 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [61]:
n = 1_000_000
matrix = np.linspace(1, n, n).reshape(2, -1)

matrix.shape

(2, 500000)

In [67]:
matrice_grossa = matrix.tolist()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [68]:
nuova_matrice = []

for i in matrice_grossa:
    for j in i:
        nuova_matrice[i][j] = sqrt(j)



TypeError: list indices must be integers or slices, not list

In [69]:
np.sqrt(matrix)

array([[   1.        ,    1.41421356,    1.73205081, ...,  707.10536697,
         707.10607408,  707.10678119],
       [ 707.10748829,  707.1081954 ,  707.1089025 , ...,  999.999     ,
         999.9995    , 1000.        ]])